name: build apk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: setup jdk 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: setup android sdk
      uses: android-actions/setup-android@v3
      
    - name: setup gradle wrapper
      run: |
        # install gradle first
        wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
        unzip -q gradle-8.2-bin.zip
        export PATH=$PATH:$PWD/gradle-8.2/bin

        # generate wrapper
        gradle wrapper --gradle-version 8.2

    - name: cache gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: make gradlew executable
      run: chmod +x gradlew
      
    - name: build debug apk
      run: ./gradlew assembleDebug
      
    - name: upload apk
      uses: actions/upload-artifact@v4
      with:
        name: applock-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: build release apk
      run: ./gradlew assembleRelease
      
    - name: upload release apk
      uses: actions/upload-artifact@v4
      with:
        name: applock-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
